/*
 * config.h - Single source of truth for the simulation's physical constants.
 *
 * These numbers describe the real protocol bridge as it runs on the target
 * hardware (lockstep Cortex-R5F inside a Zynq UltraScale+). They are GIVEN.
 * Nothing here is invented, recomputed or tuned to make a measurement look
 * better.
 *
 * The _Static_asserts at the bottom check that every derived value still
 * agrees with the givens. If somebody edits a constant, the build breaks
 * instead of silently changing what we claim to have measured.
 */
#ifndef R5F_CONFIG_H
#define R5F_CONFIG_H

#include <stdint.h>

/* ------------------------------------------------------------------ clock */

/* RP2350 boots at 150 MHz. Asserted at runtime in port_init(); both periodic
 * timers below are exact integer cycle counts only because of this value. */
#define R5F_SYS_CLK_HZ          150000000u
#define CYCLES_PER_US           (R5F_SYS_CLK_HZ / 1000000u)     /* 150 */

/* --------------------------------------------------------------- the wire */

#define UART_BAUD               115200u     /* 8N1 -> 10 bit times per byte */
#define BIT_TIME_NS             8680u       /* 8.68 us */
#define BYTE_TIME_NS            86800u      /* 86.8 us  <-- the deadline */

/* 86.8 us at 150 MHz lands on a whole number of cycles, so the byte tick can
 * be generated by a PWM slice with zero long-term drift. A 1 us hardware
 * alarm could not do this: it would quantise to 86 or 87 us. */
#define BYTE_TIME_CYCLES        13020u

/* ------------------------------------------------------------ sensor path */

/* Frame layout as given: two header bytes, one counter byte, the payload,
 * two checksum bytes.
 *
 * FRAME_PAYLOAD_BYTES is the only free parameter, and it is not free for
 * long: the frame total times the frame rate has to equal the line rate, and
 * the assertion at the bottom of this file enforces that. At 180 Hz on a
 * 115200 baud line the total must be 64, which leaves 59 for the payload.
 * A 64 byte payload would make the frame 69 bytes and 180 Hz would need
 * 12420 B/s on a line that carries 11520 - the build will say so. */
#define FRAME_HEADER_BYTES      2u
#define FRAME_COUNTER_BYTES     1u
#define FRAME_CRC_BYTES         2u
#define FRAME_PAYLOAD_BYTES     59u

#define SENSOR_FRAME_BYTES      (FRAME_HEADER_BYTES + FRAME_COUNTER_BYTES + \
                                 FRAME_PAYLOAD_BYTES + FRAME_CRC_BYTES)
#define SENSOR_FRAME_HZ         180u        /* fills the line exactly */
#define SENSOR_BYTES_PER_SEC    (SENSOR_FRAME_BYTES * SENSOR_FRAME_HZ)

/* --------------------------------------------------------------- CAN path */

#define CAN_SLOT_NS             135000u     /* 135 us per frame slot */
#define CAN_SLOT_CYCLES         20250u      /* also exact at 150 MHz */
#define CAN_FRAME_PAYLOAD       8u          /* classic CAN data length */

/* One ISO-TP transfer per second: 128 data frames carrying 8 bytes each,
 * plus 19 protocol frames (1 First Frame, 16 Flow Control frames - one per
 * block of 8 Consecutive Frames - 1 initial FC and 1 closing ACK). */
#define ISOTP_DATA_FRAMES       128u
#define ISOTP_PROTO_FRAMES      19u
#define ISOTP_FRAMES_TOTAL      147u
#define ISOTP_BLOCK_SIZE        8u

#define CAN_BURST_BYTES         1024u       /* bytes per burst, per second */
#define CAN_BURST_NS            19845000u   /* 147 * 135 us = 19.845 ms */
#define CAN_BUS_LOAD_PERMILLE   20u         /* 19.845 ms / 1 s = 2.0 % */

/* One burst per second, counted in slots because the slot timer is the only
 * clock the CAN side has. 135 us does not divide a second exactly, so the
 * period is 999.945 ms rather than 1000 ms - a 55 ppm difference, reported
 * rather than rounded away. */
#define CAN_BURST_PERIOD_SLOTS  7407u

/* ----------------------------------------------------- the whole argument */

/* During one 19.845 ms burst the UART can only push out this many bytes... */
#define UART_DRAIN_PER_BURST    228u
/* ...so this much has to sit in the ring buffer and wait. This is the number
 * the burst-profile chart is drawn against. */
#define EXPECTED_PEAK_BACKLOG   796u

#define RING_BYTES              4096u       /* ~5x margin over the peak */

/* The bridge takes the line while it drains, so the sensor stream gives up
 * exactly this many frames per second. 180 Hz -> 164 Hz. */
#define SENSOR_FRAMES_YIELDED   (CAN_BURST_BYTES / SENSOR_FRAME_BYTES)

/* ------------------------------------------------------------------- pins */

#define PIN_UART_TX             0u          /* GP0, physical pin 1 */
#define PIN_UART_RX             1u          /* GP1, physical pin 2  <- jumper */
#define PIN_PROBE_ISR           15u         /* high for the length of the RX ISR */
#define PIN_PROBE_BURST         14u         /* high for the length of a CAN burst */

/* -------------------------------------------------------------- telemetry */

#define TELEMETRY_HZ            10u
#define BURST_TRACE_SAMPLES     128u        /* 1 kHz trace across one burst */
#define BURST_TRACE_PERIOD_US   1000u

/* ----------------------------------------------------- consistency checks */

_Static_assert(BIT_TIME_NS * 10u == BYTE_TIME_NS,
               "8N1 is 10 bit times per byte");
_Static_assert(BYTE_TIME_NS * CYCLES_PER_US / 1000u == BYTE_TIME_CYCLES,
               "byte tick is not a whole number of cycles at R5F_SYS_CLK_HZ");
_Static_assert(CAN_SLOT_NS * CYCLES_PER_US / 1000u == CAN_SLOT_CYCLES,
               "CAN slot is not a whole number of cycles at R5F_SYS_CLK_HZ");
_Static_assert(BYTE_TIME_CYCLES < 65536u && CAN_SLOT_CYCLES < 65536u,
               "both periods must fit a 16-bit PWM wrap");
_Static_assert(SENSOR_BYTES_PER_SEC == UART_BAUD / 10u,
               "frame size times frame rate is not the line rate: with this "
               "payload the sensor stream either starves the line or "
               "oversubscribes it, and the ring buffer analysis does not hold");
_Static_assert(SENSOR_FRAME_BYTES ==
               FRAME_HEADER_BYTES + FRAME_COUNTER_BYTES +
               FRAME_PAYLOAD_BYTES + FRAME_CRC_BYTES,
               "frame layout does not add up to the frame size");
_Static_assert(ISOTP_DATA_FRAMES + ISOTP_PROTO_FRAMES == ISOTP_FRAMES_TOTAL,
               "ISO-TP frame accounting does not add up");
_Static_assert(ISOTP_DATA_FRAMES * CAN_FRAME_PAYLOAD == CAN_BURST_BYTES,
               "data frames do not carry the stated number of bytes");
_Static_assert(ISOTP_DATA_FRAMES / ISOTP_BLOCK_SIZE + 3u == ISOTP_PROTO_FRAMES,
               "protocol frame count does not match FF + per-block FC + ACK");
_Static_assert(ISOTP_FRAMES_TOTAL * CAN_SLOT_NS == CAN_BURST_NS,
               "burst duration does not match frame count times slot time");
_Static_assert(CAN_BURST_NS / BYTE_TIME_NS == UART_DRAIN_PER_BURST,
               "UART drain during a burst does not match the byte time");
_Static_assert(CAN_BURST_BYTES - UART_DRAIN_PER_BURST == EXPECTED_PEAK_BACKLOG,
               "expected peak backlog is not ingress minus drain");
_Static_assert(RING_BYTES > EXPECTED_PEAK_BACKLOG * 5u,
               "ring buffer no longer has the stated 5x margin");
_Static_assert((RING_BYTES & (RING_BYTES - 1u)) == 0u,
               "ring size must be a power of two for the masking index");
_Static_assert(SENSOR_FRAMES_YIELDED == 16u,
               "sensor should yield exactly 16 of its 180 frames per second");
_Static_assert(CAN_BURST_BYTES % SENSOR_FRAME_BYTES == 0u,
               "a burst must be a whole number of 64 byte wire units");
_Static_assert(CAN_BURST_PERIOD_SLOTS * CAN_SLOT_NS > 999000000u &&
               CAN_BURST_PERIOD_SLOTS * CAN_SLOT_NS < 1001000000u,
               "burst period is not within a millisecond of one second");
_Static_assert(CAN_BURST_PERIOD_SLOTS > ISOTP_FRAMES_TOTAL,
               "a burst has to finish before the next one starts");

#endif /* R5F_CONFIG_H */
